### ISSUE TITLE
Full output of selected value

### ISSUE THREAD

**Issue by svinter** [MacHu-GWU/afwf_fts_anything-project#2]
Hi, I love this workflow -- thanks for writing it!

As I'm passing the output of the workflow to other workflow steps I've created, I've discovered that the index of the selected item is being passed (e.g., the numbers 1, 2, or 3 in your sample dataset), not the full contents of the selection (such as the selected movie's title, keywords, description, etc.). I'd like to have a subsequent workflow step process the specific movie information from the selected item.  Is it possible to also pass the full contents of the selection to the next workflow step? If so, how?

If not, is it possible to access the details of the selection in the subsequent workflow step using the index being passed, and how would I do this? Thanks!

**Comment by MacHu-GWU** [comment]
@svinter sure it is doable.

The most important field you need to focus on is ``arg_field`` in the config file. As I described, it can be dynamically constructed from the data fields using ``{field_name_1}...{field_name_2}`` syntax. The output of my the alfred workflow script field is the value defined in ``arg_field``. And you are able to pass it to further alfred filter or pass it to another script field which can be customized in Python or any other programming language.

**Comment by svinter** [comment]
Works great -- thanks!
